#!/usr/bin/env python 
# -*- coding:utf-8 -*-
import random
target_number = random.randint(1, 100)
guess_times = 1
Goon = 1
min_number = 1
max_number = 100
total_times = int(input('Please set how many times do you have?'))
print('Your have 【%d】  chance to Guess!' % total_times)
guess_number = int(input('please give me a number you guess (between 1 to 100):'))


def exit_game():
    print('The correct number is:', target_number)
    print('GAME OVER !')


while Goon and guess_times <= total_times:
    if guess_number > target_number :
        print('you have Guess %d time' % guess_times)
        print('Your number (%d)is too high' % guess_number)
        max_number = guess_number
        if guess_times < total_times:
            print('Your have 【%d】  chance to Guess!' % (total_times - guess_times))
            guess_number = int(input('please give me a number(between %d to %d):' % (min_number, max_number)))
        else:
            exit_game()
        guess_times += 1
    elif guess_number < target_number :
        print('you have Guess %d time' % guess_times)
        print('Your number (%d)is too low' % guess_number)
        min_number = guess_number
        if guess_times < total_times:
            print('Your have 【%d】  chance to Guess!' % (total_times - guess_times))
            guess_number = int(input('please give me a number:(between %d to %d):' % (min_number, max_number)))
        else:
            exit_game()
        guess_times += 1
    else:
        print('Yes.the number is:【%d】' % target_number)
        print('Your Guess 【%d 】time.' % guess_times)
        Goon = 0
